// Blog Editor
export const HTML_EDITOR_CHANGE = 'HTML_EDITOR_CHANGE'
export const OPEN_EDITOR = 'TOGGLE_EDITOR'
export const CLOSE_EDITOR = 'CLOSE_EDITOR'

// Button
export const SUBMIT_ARTICLE = 'SUMMIT_ARTICLE'


// SETTING
export const SET_SLIDER_VALUE = 'SET_SLIDER_VALUE'
export const SET_GAME_PATH = 'SET_GAME_PATH'

// USER

export const USER_CREATE = 'USER_CREATE'
export const USER_DELETE = 'USER_DELETE'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOGOUT = 'USER_LOGOUT'

// AUTHENTICATE
export const AUTH_ERROR = 'AUTH_ERROR'

// LOGIN / LOGOUT
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

// EXCEPTION
export const EXCEPTION = 'EXCEPTION'

// ERROR
export const GET_ERRORS = 'GET_ERRORS'

//MESSAGES
export const CREATE_MESSAGES = 'CREATE_MESSAGES'

//TABS
export const SELECT_TAB = 'SELECT_TAB'